image: docker-hub.uncharted.software/node:18.8.0-slim


# Cache modules in between builds
cache:
  paths:
  - node_modules/

before_script:
  - apt-get update
  - apt-get -y install git
  - apt-get -y install python3
  - apt-get -y install g++
  - apt-get -y install make
  - yarn install

test:
  script:
    - yarn workspace client run lint -- --no-fix
    - yarn workspace server run lint
    - yarn workspace client run test:unit
    - yarn workspace server run test
  only:
    - merge_requests

build:
  script:
    - yarn workspace client run build
  only:
    - merge_requests

