image: docker-hub.uncharted.software/node:18.8.0-slim


# Cache modules in between builds
cache:
  paths:
  - node_modules/

before_script:
  - apt-get -y install --no-cache git
  - npm config set @uncharted:registry=https://npm.uncharted.software/
  - npm config set //npm.uncharted.software/:_authToken=${NPM_TOKEN}
  - yarn install

test:
  script:
    - yarn workspace client run lint -- --no-fix
    - yarn workspace server run lint
    - yarn workspace client run test:unit
    - yarn workspace server run test
  only:
    - merge_requests

build:
  script:
    - yarn workspace client run build
  only:
    - merge_requests

