stages:
  - test
  - prepare
  - build

.test_common:
  stage: test
  only:
    - main
    - merge_requests
  image: docker-hub.uncharted.software/node:18-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache git
    - npm config set @uncharted:registry=https://npm.uncharted.software/
    - npm config set //npm.uncharted.software/:_authToken=${NPM_TOKEN}
    - yarn install

lint:
  extends: .test_common
  script:
    - yarn run lint:ci
    - yarn run prettier:ci

test:
  extends: .test_common
  script:
    - yarn workspace client run test:unit
    - yarn workspace server run test

# Jobs don't share their local env variables. So Setup up variables you want to share and save it to a file.
# The file can be passed to other jobs as an artifact
environment:
  stage: prepare
  only:
    - main
    - merge_requests
    - tags
  image: docker-hub.uncharted.software/alpine
  artifacts:
    paths:
      - ci.env
    expire_in: 1 week
  script:
    - echo "--- Preparing environment vars ---"
    - >
      case ${CI_COMMIT_REF_NAME} in

        "${CI_COMMIT_TAG}") export DOCKER_TAG="${CI_COMMIT_TAG}" ;;

        main) export DOCKER_TAG="latest" ;;

        *) echo "Defaulting to $CI_COMMIT_REF_NAME";
           export DOCKER_TAG="$CI_COMMIT_REF_NAME" ;;

      esac
    - 'echo "DOCKER_TAG: ${DOCKER_TAG}"'
    # prepare should fail if the docker tag version is empty
    - if [ -z "${DOCKER_TAG}" ]; then exit 1; fi
    - echo "DOCKER_TAG=${DOCKER_TAG}" > ci.env

build:
  stage: build
  only:
    - main
    - merge_requests
    - tags
  dependencies:
    - environment
  image: docker.uncharted.software/worldmodeler/causemos-ci:1.0.0
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    # Set env vars passed from prepare stage
    - export $(grep -v '^#' ci.env | xargs)
  script:
    - echo "--- Building Causemos docker image ---"
    - echo VERSION=${DOCKER_TAG}

    # Build and push the docker image
    - >
      if [ ${CI_PIPELINE_SOURCE} != "merge_request_event" ]; then
        DOCKER_PARAMS="--push --provenance=false"
      else
        DOCKER_PARAMS=""
      fi
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - VERSION=${DOCKER_TAG} docker buildx bake causemos ${DOCKER_PARAMS}
