image: docker-hub.uncharted.software/mhart/alpine-node:12

# Cache modules in between builds
cache:
  paths:
  - node_modules/

before_script:
  - npm config set @uncharted:registry=https://npm.uncharted.software/
  - npm config set //npm.uncharted.software/:_authToken=${NPM_TOKEN}
  - yarn install

lint:
  script:
    - yarn workspace client run lint -- --no-fix
    - yarn workspace server run lint
  only:
    - merge_requests

test-unit:
  script:
    - yarn workspace client run test:unit
    - yarn workspace server run test
  only:
    - merge_requests

build:
  script:
    - yarn workspace client run build
  only:
    - merge_requests

