stages:
  - test
  - prepare
  - build

.test_common:
  stage: test
  only:
    - main
    - merge_requests
  image: docker-hub.uncharted.software/mhart/alpine-node:16
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache git
    - npm config set @uncharted:registry=https://npm.uncharted.software/
    - npm config set //npm.uncharted.software/:_authToken=${NPM_TOKEN}
    - yarn install

lint:
  extends: .test_common
  script:
    - yarn run lint:ci

test:
  extends: .test_common
  script:
    - yarn workspace client run test:unit
    - yarn workspace server run test

# Jobs don't share it's local env variables. So Setup up variables you want to share and save it to a file.
# The file can be passed to other jobs as an artifacts
environment:
  stage: prepare
  only:
    - main
    - merge_requests
    - tags
  image: docker-hub.uncharted.software/alpine
  artifacts:
    paths:
      - ci.env
    expire_in: 1 week
  script:
    - echo "--- Preparing environment vars ---"
    - >
      case ${CI_COMMIT_REF_NAME} in

        "${CI_COMMIT_TAG}") export DOCKER_TAG="${CI_COMMIT_TAG}" ;;

        *) export DOCKER_TAG="latest" ;;

      esac
    - 'echo "DOCKER_TAG: ${DOCKER_TAG}"'
    # prepare should fail if the docker tag version is empty
    - if [ -z "${DOCKER_TAG}" ]; then exit 1; fi
    - echo "DOCKER_TAG=${DOCKER_TAG}" > ci.env

build:
  stage: build
  only:
    - main
    - merge_requests
    - tags
  dependencies:
    - environment
  image: docker-hub.uncharted.software/docker:latest
  services:
    - name: docker-hub.uncharted.software/docker:dind
      alias: docker
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    # Set env vars passed from prepare stage
    - export $(grep -v '^#' ci.env | xargs)
  script:
    - echo "--- Building wm-server docker image ---"
    - echo VERSION=${DOCKER_TAG}

    # Build and push the docker image
    - docker build -t docker.uncharted.software/worldmodeler/wm-server:${DOCKER_TAG} .
    # Push docker image on main branch or when a tag is created, i.e., do not push on merge request events.
    - if [ ${CI_PIPELINE_SOURCE} != "merge_request_event" ]; then docker push docker.uncharted.software/worldmodeler/wm-server:${DOCKER_TAG}; fi
