const CONTRADICTION = Object.freeze({
  ALL_SUPPORTING: 0,
  SOME_REFUTING: 1,
  ALL_REFUTING: 2
});

const CONTRADICTION_MAP = Object.freeze({
  [CONTRADICTION.ALL_SUPPORTING]: 'None',
  [CONTRADICTION.SOME_REFUTING]: 'Some',
  [CONTRADICTION.ALL_REFUTING]: 'All'
});

export default {
  CONTRADICTION,
  CONTRADICTION_MAP
};
