# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tiles.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btiles.proto\x12\x05tiles\"o\n\tTileStats\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12\x0b\n\x03sum\x18\x02 \x01(\x01\x12\x0b\n\x03\x61vg\x18\x03 \x01(\x01\x12\x13\n\x0bs_sum_t_sum\x18\x04 \x01(\x01\x12\x14\n\x0cs_sum_t_mean\x18\x05 \x01(\x01\x12\x0e\n\x06weight\x18\x06 \x01(\x01\"\x88\x01\n\x08TileBins\x12)\n\x05stats\x18\x01 \x03(\x0b\x32\x1a.tiles.TileBins.StatsEntry\x12\x11\n\ttotalBins\x18\x02 \x01(\r\x1a>\n\nStatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.tiles.TileStats:\x02\x38\x01\"7\n\tTileCoord\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01z\x18\x03 \x01(\r\x12\t\n\x01t\x18\x04 \x01(\x03\"F\n\x04Tile\x12\x1f\n\x05\x63oord\x18\x01 \x01(\x0b\x32\x10.tiles.TileCoord\x12\x1d\n\x04\x62ins\x18\x02 \x01(\x0b\x32\x0f.tiles.TileBinsB-Z+gitlab.uncharted.software/WM/wm-proto/tilesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tiles_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+gitlab.uncharted.software/WM/wm-proto/tiles'
  _TILEBINS_STATSENTRY._options = None
  _TILEBINS_STATSENTRY._serialized_options = b'8\001'
  _TILESTATS._serialized_start=22
  _TILESTATS._serialized_end=133
  _TILEBINS._serialized_start=136
  _TILEBINS._serialized_end=272
  _TILEBINS_STATSENTRY._serialized_start=210
  _TILEBINS_STATSENTRY._serialized_end=272
  _TILECOORD._serialized_start=274
  _TILECOORD._serialized_end=329
  _TILE._serialized_start=331
  _TILE._serialized_end=401
# @@protoc_insertion_point(module_scope)
